@startuml

control listener
control processor1
queue responses1

control processor2
queue responses2

queue requests
control kafka_rd

listener -> processor1: spawn
activate processor1
processor1 -> responses1: create
processor1 --> requests: send
kafka_rd <-- requests: receive
kafka_rd --> responses1: send
processor1 <-- responses1: receive
deactivate processor1

listener -> processor2: spawn
activate processor2
processor2 -> responses2: create
processor2 --> requests: send
kafka_rd <-- requests: receive
kafka_rd --> responses2: send
processor2 <-- responses2: receive
deactivate processor2

@enduml