@startuml

actor client
control listener
control reader
control writer
queue requests
queue responses
control kafka
 
activate kafka
activate listener

client -> listener: connect
client <- listener: accept

listener -> responses: create
listener -> reader: spawn
activate reader
listener -> writer: spawn
activate writer

client -> reader: req
reader -> requests: req
requests -> kafka: req
responses <- kafka: res
writer <- responses: res
client <- writer: res

@enduml